name: release

on:
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#release
  release:
    types: [prereleased]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release_name:
        description: The prerelease name
        type: string
        required: true

jobs:
  release-artifact:
    runs-on: ubuntu-latest
    steps:
      - id: specification-mapper-release
        uses: shihyuho/go-jenkins-trigger@v1
        with:
          jenkins-url: "${{ secrets.JENKINS_URL }}"
          jenkins-user: "${{ secrets.JENKINS_USER }}"
          jenkins-pat: "${{ secrets.JENKINS_PAT }}"
          insecure: "true"
          job: "${{ github.action }}"
          params: "ref=${{ github.ref }}"
          wait: false
