# 發佈版本
name: Publish a New Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - jakarta
    types:
      - closed

jobs:
  get-version:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'bot/bump-version')
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - id: get-version
        run: echo "version=$(make version)" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.get-version.outputs.version }}
  trigger-jenkins:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - id: specification-mapper-release
        uses: shihyuho/go-jenkins-trigger@v1
        with:
          jenkins-url: "${{ secrets.JENKINS_URL }}"
          jenkins-user: "${{ secrets.JENKINS_USER }}"
          jenkins-pat: "${{ secrets.JENKINS_PAT }}"
          job: "${{ github.action }}"
          params: "ref=${{ github.sha }},tag=${{ needs.get-version.outputs.version }},"
          wait: false
